services:
  backend:
    build: ./backend
    environment:
      FLASK_ENV: production
    networks:
      - app-network
    volumes:
      - ./backend:/app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge